# Generated by Django 3.0.7 on 2020-06-11 11:59

from django.db import migrations
from django.contrib.auth.hashers import make_password

from api.proto.auth_pb2 import Admin


def add_default_admin(apps, schema_editor):
    User = apps.get_model("auth", "User")
    user = User.objects.create(
        username="online-store@localhost.com",
        email="online-store@localhost.com",
        password=make_password("123"),
    )
    user.save()

    Profile = apps.get_model("backend", "Profile")
    admin = Profile(
        user=user,
        role=Admin,
    )
    admin.save()

    return


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(add_default_admin),
    ]
