# Generated by Django 3.0.4 on 2020-03-26 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
